const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
const SET_SIGNED_UP_USER = 'SET_SIGNED_UP_USER';

export default {
  SIGN_UP_REQUEST,
  SIGN_UP_ERROR,
  SET_SIGNED_UP_USER,
};
