const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
const AUTH_ERROR = 'AUTH_ERROR';
const SET_SIGNED_UP_USER = 'SET_SIGNED_UP_USER';
const IS_USER_EXISTS = 'IS_USER_EXISTS';
const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';

export default {
  SIGN_UP_REQUEST,
  AUTH_ERROR,
  SET_SIGNED_UP_USER,
  IS_USER_EXISTS,
  SIGN_IN_REQUEST,
};
